# Generated by Django 5.2.3 on 2025-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('Jounal', 'Journal'), ('Life updates', 'Life updates'), ('Travel stories', 'Travel stories'), ('Personal growth', 'Personal growth')], default='Jounal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
