# Generated by Django 5.2.3 on 2025-07-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_all_manage', 'Can all changed models')]},
        ),
    ]
