# Generated by Django 5.2.3 on 2025-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_is_active_alter_blog_content_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('JL', 'Journal'), ('LU', 'Life updates'), ('TS', 'Travel stories'), ('PG', 'Personal growth')], default='JL', max_length=3),
        ),
    ]