# Generated by Django 5.2.3 on 2025-06-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
